addr: 127.0.0.1:4842
ssl:
  addr: 127.0.0.1:4843
  enable: false
passwords:
  - cyejing123
routes:
  - id: na0mdwfr0lfuv4rubvt4gsg805uofhhk
    order: 100
    host: localhost1:4842
    filters:
      - name: proxy
        params:
          uri: "http://localhost:8088"
  - id: f1xb758a1hsrkguxtryjjt4swakayrf8
    order: 120
    path: /static
    filters:
      - name: rewrite
        params:
          regex: "/static/(.*)"
          replacement: "/$1"
      - name: resource
        params:
          root: ""
  - id: gixxjmbjyjpfdzoe9u1z7jblxiea6czf
    order: 200
    host: localhost:4842
    filters:
      - name: socks
      - name: resource
        params:
          root: ""
instances:
  - group: example
    uri: https://www.baidu.com
