addr: 127.0.0.1:4842
ssl:
  addr: 127.0.0.1:4843
  enable: false
routes:
  - id: 196105db9a384d7a93f8102ae46684cb
    order: 100
    host: localhost:4842
    filters:
      - name: proxy
        params:
          uri: "http://localhost:8890"
  - id: f1xb758a1hsrkguxtryjjt4swakayrf8
    order: 20
    path: /static
    filters:
      - name: rewrite
        params:
          regex: "/file/(.*)"
          replacement: "/$1"
      - name: resource
        params:
          root: "./"
instances:
  - group: example
    uri: https://www.baidu.com
